COMPONENT_PATH := $(abspath $(lastword $(dir $(MAKEFILE_LIST))))

UTILS_SRCDIRS := $(COMPONENT_PATH)
UTILS_SRCDIRS += $(COMPONENT_PATH)/Bit_Wise

UTILS_INCDIRS := $(COMPONENT_PATH)
UTILS_INCDIRS += $(COMPONENT_PATH)/Bit_Wise


ifdef CONFIG_CUSTOM_PRINTF_USE
UTILS_SRCDIRS += $(COMPONENT_PATH)/printf
UTILS_INCDIRS += $(COMPONENT_PATH)/printf

ifdef CONFIG_ALIAS_STD_FUNCTION_NAMES
UTILS_DEFINES := PRINTF_ALIAS_STANDARD_FUNCTION_NAMES_SOFT='1'
else
UTILS_DEFINES := PRINTF_ALIAS_STANDARD_FUNCTION_NAMES_SOFT='0'
endif

ifdef CONFIG_PRINTF_DECIMAL_SPECIFIERS_USE
UTILS_DEFINES += PRINTF_SUPPORT_DECIMAL_SPECIFIERS='1'
else
UTILS_DEFINES += PRINTF_SUPPORT_DECIMAL_SPECIFIERS='0'
endif

ifdef CONFIG_PRINTF_EXPONENTIAL_SPECIFIERS_USE
UTILS_DEFINES += PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS='1'
else
UTILS_DEFINES += PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS='0'
endif

ifdef CONFIG_PRINTF_SERIAL_PORT
UTILS_DEFINES += CONFIG_PRINTF_SERIAL_PORT=$(CONFIG_PRINTF_SERIAL_PORT)
endif

endif