COMPONENT_PATH := $(abspath $(lastword $(dir $(MAKEFILE_LIST))))

ifdef CONFIG_OS_FREERTOS_USE

RTOS_SRCDIRS := $(COMPONENT_PATH)/FreeRTOS
RTOS_SRCDIRS += $(COMPONENT_PATH)/FreeRTOS/Protable/GCC
RTOS_SRCDIRS += $(COMPONENT_PATH)/FreeRTOS/Protable/MemMang

RTOS_INCDIRS := $(COMPONENT_PATH)/FreeRTOS/include

endif